---
system:
  certificateFilePath: "/environment/greengrass/v2/certificates/certificate.pem"
  privateKeyPath: "/environment/greengrass/v2/certificates/privateKey.pem"
  rootCaPath: "/environment/greengrass/v2/certificates/rootCA.pem"
  rootpath: "/greengrass/v2"
  thingName: "RatchetWorkshop_Core"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "[2.0.5]"
    configuration:
      awsRegion: "[us-west-2]"
      iotRoleAlias: "RatchetWorkshopRoleAlias"
      iotDataEndpoint: "[device-data-prefix-ats.iot.us-west-2.amazonaws.com]"
      iotCredEndpoint: "[device-credentials-prefix.credentials.iot.us-west-2.amazonaws.com]"